# Generated by Django 4.2 on 2025-02-15 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('2cd52028-f999-4827-af0a-b2ae7d61fe1a'), editable=False, unique=True),
        ),
    ]
