# Generated by Django 4.2 on 2025-03-06 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='local_unit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('8fccb184-e36c-456c-a7fc-631adf1e2930'), editable=False, unique=True),
        ),
    ]
