# Generated by Django 4.2 on 2025-03-06 17:45

import admin_dashboard.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_address_local_unit_name_alter_address_ward_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(default='profile/default.jpg', upload_to=admin_dashboard.models.profile_location, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('f0e6a162-7d90-42bf-bb99-83e1c2f14e73'), editable=False, unique=True),
        ),
    ]
